
import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import LoginBtn from './LoginBtn'
import LogoutBtn from './LogoutBtn'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">RoommateFinder</Link>
          <LoginBtn></LoginBtn>
          <LogoutBtn />
          <Link href={"/register"}>회원가입</Link>
        </div>
        {children}
      </body>
    </html>
  )
}
